Cohda_App_GLOSA.RX.DebugLevel = 5 # NOTICE != -1
Cohda_App_GLOSA.ENABLE = 1 # != 0
Cohda_App_GLOSA.REC_ENABLE = 1 # != 0
Cohda_App_GLOSA.LaneSelectionPolicy = 1 # != 0
Cohda_App_GLOSA.REC_HMI_TIME_MAX = 5000 # != 8000
Cohda_App_GLOSA.REC_RECOM_MINSPEED = 0 # != 7
Cohda_App_GLOSA.HV_INHIBIT_MASK = 0x0 # != 0x2a408
